### ISSUE TITLE
The getter 'height' was called on null in aspect ratio

### ISSUE THREAD

**Issue by AlexV525** [rhymelph/r_scan#20]
## Environment
**Flutter Version:** 1.17.0
**Android Version:** Android 10
**Device Model:** Emulator / OnePlus A6010
**Dependency Version:** 0.1.4+1

## Step to reproduce

1. Place a widget in `build` which is the same as demo:
```dart
if (_controller != null) // Check controller valid
  AspectRatio(
    aspectRatio: _controller.value.aspectRatio,
    child: RScanCamera(_controller),
  )
```
2. Init cameras with:
```dart
availableRScanCameras().then((List<RScanCameraDescription> s) {
  rScanCameras = s;
  if (rScanCameras.length > 0) {
    _controller = RScanCameraController(
      firstCameraDescription,
      RScanCameraResolutionPreset.max,
    )
        ..addListener(onScan);
        ..initialize().then((dynamic _) {
          if (mounted) setState(() {});
        });
  }
}
```
3. The error occurred.

## Error log
```
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building ScanQrCodePage(dirty, state: _ScanQrCodePageState#42dbb):
The getter 'height' was called on null.
Receiver: null
Tried calling: height

The relevant error-causing widget was: 
  ScanQrCodePage file:///Users/alex/Documents/OpenJMU/lib/openjmu_route.dart:188:17
When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      RScanCameraValue.aspectRatio (package:r_scan/src/r_scan_camera.dart:133:41)
......
```

**Comment by AlexV525** [comment]
Sorry, mistaking missing initialized flag judgement. 😢
