### ISSUE TITLE
条形码扫不出来，二维码扫完后报错

### ISSUE THREAD

**Issue by kazeik** [rhymelph/r_scan#30]
嵌入进来后，在常规的药品商品条形码扫码，无法识别。
换成手机微信的二维码后，可以扫出来，但返回后，程序崩溃了。
![image](https://user-images.githubusercontent.com/2524383/88605047-69b9f100-d0ab-11ea-816d-d302f8205bb4.png)

**Comment by kazeik** [comment]
无法贴图片。
I/CameraManager(14968): Using legacy camera HAL.
I/CameraDeviceState(14968): Legacy camera service transitioning to state CONFIGURING
I/RequestThread-0(14968): Configure outputs: 2 surfaces configured.
D/Camera  (14968): app passed NULL surface
I/CameraDeviceState(14968): Legacy camera service transitioning to state IDLE
I/RequestQueue(14968): Repeating capture request set.
W/LegacyRequestMapper(14968): convertRequestMetadata - control.awbRegions setting is not supported, ignoring value
W/LegacyRequestMapper(14968): Only received metering rectangles with weight 0.
W/LegacyRequestMapper(14968): Only received metering rectangles with weight 0.
I/CameraDeviceState(14968): Legacy camera service transitioning to state CAPTURING
I/flutter (14968): result = RScanResult{type: RScanBarType.qr_code, message: https://u.wechat.com/ECExPdw4NYMMs1jGWLVQ5UM, points: [RScanPoint{x: null, y: null}, RScanPoint{x: null, y: null}, RScanPoint{x: null, y: null}, RScanPoint{x: null, y: null}]}
I/RequestQueue(14968): Repeating capture request cancelled.
E/BufferQueueProducer(14968): [SurfaceTexture-1-14968-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(14968): [SurfaceTexture-1-14968-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(14968): [SurfaceTexture-1-14968-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(14968): [SurfaceTexture-1-14968-1] cancelBuffer: BufferQueue has been abandoned
E/BufferQueueProducer(14968): [SurfaceTexture-1-14968-1] cancelBuffer: BufferQueue has been abandoned
W/ImageReader_JNI(14968): ImageReader#close called before Image#close, consider calling Image#close first
E/AndroidRuntime(14968): FATAL EXCEPTION: pool-3-thread-1
E/AndroidRuntime(14968): Process: com.jingsong.deliverer, PID: 14968
E/AndroidRuntime(14968): java.lang.RuntimeException: ImageReaderContext is not initialized
E/AndroidRuntime(14968): 	at android.media.ImageReader.nativeImageSetup(Native Method)
E/AndroidRuntime(14968): 	at android.media.ImageReader.acquireNextSurfaceImage(ImageReader.java:327)
E/AndroidRuntime(14968): 	at android.media.ImageReader.acquireNextImage(ImageReader.java:375)
E/AndroidRuntime(14968): 	at android.media.ImageReader.acquireLatestImage(ImageReader.java:277)
E/AndroidRuntime(14968): 	at com.rhyme.r_scan.RScanCamera.RScanCamera$4$1.run(RScanCamera.java:293)
E/AndroidRuntime(14968): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/AndroidRuntime(14968): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/AndroidRuntime(14968): 	at java.lang.Thread.run(Thread.java:818)
I/Process (14968): Sending signal. PID: 14968 SIG: 9
I/Process (14968): Sending signal. PID: 14968 SIG: 9
Lost connection to device.

**Comment by huangsir0** [comment]
@kazeik 我也遇到一样的问题，扫码获取到结果程序闪退，或者到扫码界面直接返回也会闪退。

**Comment by huangsir0** [comment]
亲解决了吗

**Comment by huangsir0** [comment]
I/RequestQueue( 8541): Repeating capture request cancelled.
I/flutter ( 8541): didChangeMetrics  ：宽：1080.0 高：1920.0
W/MessageQueue( 8541): Handler (android.graphics.SurfaceTexture$1) {cdf7d81} sending message to a Handler on a dead thread
W/MessageQueue( 8541): java.lang.IllegalStateException: Handler (android.graphics.SurfaceTexture$1) {cdf7d81} sending message to a Handler on a dead thread
W/MessageQueue( 8541): 	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
W/MessageQueue( 8541): 	at android.os.Handler.enqueueMessage(Handler.java:631)
W/MessageQueue( 8541): 	at android.os.Handler.sendMessageAtTime(Handler.java:600)
W/MessageQueue( 8541): 	at android.os.Handler.sendMessageDelayed(Handler.java:570)
W/MessageQueue( 8541): 	at android.os.Handler.sendEmptyMessageDelayed(Handler.java:534)
W/MessageQueue( 8541): 	at android.os.Handler.sendEmptyMessage(Handler.java:519)
W/MessageQueue( 8541): 	at android.graphics.SurfaceTexture.postEventFromNative(SurfaceTexture.java:376)
