### ISSUE TITLE
 java.lang.NoSuchMethodError: No interface method sort

### ISSUE THREAD

**Issue by LNyears** [rhymelph/r_scan#42]
r_scan: ^0.1.5
android: 6.0
vivo
扫码后报错导致应用奔溃
E/AndroidRuntime(31092): java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)

**Comment by LNyears** [comment]
E/AndroidRuntime( 7330): java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
E/AndroidRuntime( 7330): 	at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
E/AndroidRuntime( 7330): 	at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
E/AndroidRuntime( 7330): 	at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
E/AndroidRuntime( 7330): 	at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
E/AndroidRuntime( 7330): 	at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
E/AndroidRuntime( 7330): 	at com.google.zxing.MultiFormatReader.decode(MultiFormatReader.java:57)
E/AndroidRuntime( 7330): 	at com.rhyme.r_scan.RScanCamera.RScanCamera$3$1.run(RScanCamera.java:401)
E/AndroidRuntime( 7330): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/AndroidRuntime( 7330): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/AndroidRuntime( 7330): 	at java.lang.Thread.run(Thread.java:818)
I/BufferQueueProducer( 7330): [SurfaceTexture-1-7330-1](this:0x7f826f9800,id:2,api:4,p:392,c:7330) queueBuffer: slot 7 is dropped, handle=0x7f86de6660

**Comment by IonVillarreal** [comment]
Hi, I have the same problem in Android 5, it seems that method works from api 24
